name: yolo_flutter
description: A flutter project that uses tflite_flutter and NMS to show YOLOv8 output
version: 0.5.0+5

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: '>=3.29.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  tflite_flutter: ^0.12.1
  image_picker: ^1.2.1
  dartcv4: ^2.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

hooks:
  user_defines:
    dartcv4:
      include_modules:
        - imgcodecs
        - imgproc
      exclude_modules:
        - calib3d
        - features2d
        - objdetect
        - photo
        - stitching

flutter:
  uses-material-design: true

  assets:
    - assets/models/yolov11n.tflite
